language: c
sudo: required
service: docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
script:
  - wget https://raw.githubusercontent.com/xapi-project/xs-opam/master/tools/xs-opam-ci.env
  - . xs-opam-ci.env
  - bash -ex .travis-docker.sh
env:
  global:
    - PACKAGE="xenops-cli"
    - BASE_REMOTE_BRANCH="REQ-627"
    - PINS="xenops-cli:."
  matrix:
    - PACKAGE="xenops-cli"
